// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI4oCMcL4Z5Y9RQI3gTBQd7PU3mbfrmrQ',
    appId: '1:2858435678:web:3d62647c15069a762be0cf',
    messagingSenderId: '2858435678',
    projectId: 'flutterestate',
    authDomain: 'flutterestate.firebaseapp.com',
    storageBucket: 'flutterestate.firebasestorage.app',
    measurementId: 'G-5Z971J3M3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgCt0y0blbipFGe-F6_BTX7gX1lHEcOxo',
    appId: '1:2858435678:android:8f76c40e861f365f2be0cf',
    messagingSenderId: '2858435678',
    projectId: 'flutterestate',
    storageBucket: 'flutterestate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5ADEkmc4VKci7NsbCRWS6SMSTAcsrdY8',
    appId: '1:2858435678:ios:298756a7e45bba5c2be0cf',
    messagingSenderId: '2858435678',
    projectId: 'flutterestate',
    storageBucket: 'flutterestate.firebasestorage.app',
    iosBundleId: 'com.example.koorUiKit',
  );
}
